---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Atlas'
    value: 'WinreFallbackFixed'
    data: '1'
    type: REG_SZ
